# Generated by Django 4.1.5 on 2023-03-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coursemodel_coursestudentmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursestudentmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursestudentmodel',
            name='student_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_student_student_profle', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudentmodel',
            unique_together={('course', 'student_profile')},
        ),
        migrations.RemoveField(
            model_name='coursestudentmodel',
            name='student',
        ),
    ]
