# Generated by Django 4.1.5 on 2023-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_exammodel_assignmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='time_start',
            field=models.TimeField(auto_now=True),
        ),
    ]
