# Generated by Django 4.1.5 on 2023-03-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_remove_exammodel_time_start_assignmentmodel_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmodel',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
