# Generated by Django 4.1.5 on 2023-03-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_assignmentmodel_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='correct',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='wrong',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
