# Generated by Django 4.1.5 on 2023-03-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_assignmentmodel_correct_assignmentmodel_wrong'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_matrix', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='matrix')),
                ('questions', models.ManyToManyField(blank=True, to='Quiz.quesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_sample', models.CharField(max_length=20)),
                ('quiz_matrixs', models.ManyToManyField(blank=True, to='Quiz.quizmatrix')),
            ],
        ),
    ]
