# Generated by Django 4.1.5 on 2023-03-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_quizmatrix_quizsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=800, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizmatrix',
            name='questions',
        ),
        migrations.AlterField(
            model_name='quizmatrix',
            name='name_of_matrix',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizsample',
            name='name_of_sample',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='quizmatrix',
            name='question_samples',
            field=models.ManyToManyField(blank=True, to='Quiz.quessample'),
        ),
    ]
