# Generated by Django 4.1.5 on 2023-03-08 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_quessample_remove_quizmatrix_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='assignment_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_season', to='Quiz.assignmentseason'),
        ),
    ]
