# Generated by Django 4.1.5 on 2023-03-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_assignmentseason_assignmentmodel_assignment_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentseason',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='ma_de',
            field=models.CharField(max_length=50),
        ),
    ]
