# Generated by Django 4.1.5 on 2023-03-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_alter_assignmentseason_name_alter_exammodel_ma_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_matrix', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuesMatrixQuesSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='Quiz.quesmatrix')),
                ('question_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sample', to='Quiz.quessample')),
            ],
            options={
                'unique_together': {('matrix', 'question_sample')},
            },
        ),
        migrations.DeleteModel(
            name='QuizMatrix',
        ),
        migrations.AlterField(
            model_name='quizsample',
            name='quiz_matrixs',
            field=models.ManyToManyField(blank=True, to='Quiz.quesmatrix'),
        ),
    ]
