# Generated by Django 4.1.5 on 2023-03-09 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_quesmatrix_quesmatrixquessample_delete_quizmatrix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizStructureSampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=200)),
                ('quiz_matrixs', models.ManyToManyField(blank=True, to='Quiz.quesmatrix')),
            ],
        ),
        migrations.CreateModel(
            name='QuizStructureWithQuesMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quesmatrixquessample')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quizstructuresamplemodel')),
            ],
            options={
                'unique_together': {('structure', 'matrix')},
            },
        ),
        migrations.DeleteModel(
            name='QuizSample',
        ),
    ]
