# Generated by Django 4.1.5 on 2023-03-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_quizstructuresamplemodel_quizstructurewithquesmatrix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizstructuresamplemodel',
            name='quiz_matrixs',
        ),
    ]
