# Generated by Django 4.1.5 on 2023-03-09 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_remove_quizstructuresamplemodel_quiz_matrixs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesMatrixQuesSample',
            new_name='QuesMatrixQuesSampleRelated',
        ),
        migrations.RenameModel(
            old_name='QuizStructureWithQuesMatrix',
            new_name='QuizStructureWithQuesMatrixRelated',
        ),
        migrations.AlterField(
            model_name='quizstructurewithquesmatrixrelated',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quesmatrix'),
        ),
    ]
