# Generated by Django 4.1.5 on 2023-03-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0015_rename_quesmatrixquessample_quesmatrixquessamplerelated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quesmatrix',
            name='name_of_matrix',
        ),
        migrations.AddField(
            model_name='quesmatrix',
            name='name',
            field=models.CharField(default='Tên ma trận câu hỏi', max_length=200),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='ma_de',
            field=models.CharField(default='Mã đề', max_length=50),
        ),
        migrations.CreateModel(
            name='ExamWithQuesRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.exammodel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quesmodel')),
            ],
            options={
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
