# Generated by Django 4.1.5 on 2023-03-09 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_coursestudentmodel_unique_together_and_more'),
        ('Quiz', '0016_remove_exammodel_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('status', models.CharField(blank=True, default='Assigned', max_length=10, null=True)),
                ('answers', models.TextField(blank=True, null=True)),
                ('wrong', models.IntegerField(blank=True, default=-1, null=True)),
                ('correct', models.IntegerField(blank=True, default=-1, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coursemodel')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Quiz.exammodel')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.assignmentseason')),
            ],
            options={
                'unique_together': {('season', 'course')},
            },
        ),
        migrations.DeleteModel(
            name='AssignmentModel',
        ),
    ]
