# Generated by Django 4.1.5 on 2023-03-09 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_coursestudentmodel_unique_together_and_more'),
        ('Quiz', '0017_assignmentrelated_delete_assignmentmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentrelated',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignmentrelated',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentrelated',
            unique_together={('season', 'student')},
        ),
        migrations.RemoveField(
            model_name='assignmentrelated',
            name='course',
        ),
    ]
