# Generated by Django 4.1.5 on 2023-01-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TableChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=20)),
                ('ho_va_chu_lot', models.CharField(max_length=50)),
                ('ten', models.CharField(max_length=20)),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lop_hoc', to='quizcore.tableclass')),
            ],
        ),
        migrations.CreateModel(
            name='TableQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answers', models.ManyToManyField(to='quizcore.tableanswer')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='quizcore.tablechapter')),
                ('correct_answers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_answers', to='quizcore.tableanswer')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='quizcore.tablelevel')),
            ],
        ),
        migrations.CreateModel(
            name='TableExamStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.ManyToManyField(to='quizcore.tablechapter')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizcore.tableclass')),
            ],
        ),
        migrations.CreateModel(
            name='TableExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_de', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('exam_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_structure', to='quizcore.tableexamstructure')),
                ('questions', models.ManyToManyField(to='quizcore.tablequestion')),
            ],
        ),
        migrations.CreateModel(
            name='TableAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('current_answers', models.ManyToManyField(to='quizcore.tableanswer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='quizcore.tableexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quizcore.tablestudent')),
            ],
        ),
    ]
