# Generated by Django 4.1.5 on 2023-03-06 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TableChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableExamStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('chapters', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Chap 1'), ('b', 'Chap 2'), ('c', 'Chap 3'), ('d', 'Chap 4')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableHelloThai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TableLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='quizcore.tablechapter')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='quizcore.tablelevel')),
            ],
        ),
        migrations.CreateModel(
            name='TableExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_de', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('exam_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_structure', to='quizcore.tableexamstructure')),
                ('questions', models.ManyToManyField(to='quizcore.tablequestion')),
            ],
        ),
        migrations.CreateModel(
            name='TableAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('current_answers', models.ManyToManyField(to='quizcore.tableanswer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='quizcore.tableexam')),
                ('student2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tableanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizcore.tablequestion'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=20, null=True)),
                ('ho_va_chu_lot', models.CharField(max_length=50, null=True)),
                ('ten', models.CharField(max_length=20, null=True)),
                ('lop_hoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lop_hoc', to='quizcore.tableclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
