# Generated by Django 4.1.5 on 2023-03-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lop_hoc',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='TableHelloThai',
        ),
        migrations.RenameField(
            model_name='tableassign',
            old_name='student2',
            new_name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TableClass',
        ),
    ]
