# Generated by Django 4.1.5 on 2023-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableexamstructure',
            name='year',
            field=models.IntegerField(),
        ),
    ]
