# Generated by Django 4.1.5 on 2023-01-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizcore', '0002_alter_tableexamstructure_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablequestion',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='tablequestion',
            name='correct_answers',
        ),
        migrations.AddField(
            model_name='tableanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizcore.tablequestion'),
        ),
    ]
