# Generated by Django 4.1.5 on 2023-02-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizcore', '0003_remove_tablequestion_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableHelloThai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
    ]
