# Generated by Django 4.1.5 on 2023-02-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizcore', '0004_tablehellothai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablehellothai',
            name='note',
            field=models.CharField(max_length=20),
        ),
    ]
