# Generated by Django 4.1.5 on 2023-02-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizcore', '0005_alter_tablehellothai_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableHelloThai',
        ),
    ]
